### ISSUE TITLE
Crash on Startup (Client and Server)

### ISSUE THREAD

**Issue by OxiiGiin1** [DevDyna/Chipped-Express#1]
[crash-2024-02-03_14.45.24-client.txt](https://github.com/DevDyna/Chipped-Express/files/14154240/crash-2024-02-03_14.45.24-client.txt)

**Comment by DevDyna** [comment]
this was caused by [Oculus and rubidium](https://github.com/Asek3/Oculus/issues/395) not from Chipped-Express
