### ISSUE TITLE
version dependency load failure

### ISSUE THREAD

**Issue by AceDrago** [DevDyna/Chipped-Express#2]
as the title says, is not wanting to load correctly on any version other but 1.20.2 because if it is 1.19.2 then it will scream that is needs chipped version 2.1.5 for 1.20.2 as well as needing Minecraft 1.20.

link of screenshot with the proof
https://imgur.com/a/56iDGRd

**Comment by DevDyna** [comment]
thank for feedback!

**Comment by DevDyna** [comment]
closed on https://github.com/DevDyna/Chipped-Express/commit/81a1d8f40354d8b9b28d9a957be06331f953b350
